In [19]:
def square(num):
    print(num**2)
    def greet():
        print("\t This is a greet function")    
    def welcome():
        return"\t This is welcome funtion"
#     greet()
#     print(welcome())
    print("returning a function")
    if num==3:
        return greet # didin't use greet() bcoz wanted to implement it by myfunc().
    else:
        return welcome
    

In [20]:
square(3)

9
returning a function


<function __main__.square.<locals>.greet()>

In [21]:
myfunc=square(3)

9
returning a function


In [23]:
myfunc()

	 This is a greet function


In [26]:
def hello():
    return "HI! How r u?"
def other(some_def_func):
    print("Other code run here")
    print(some_def_func())
    
hello()

'HI! How r u?'

In [27]:
other(hello)

Other code run here
HI! How r u?


In [12]:
def decorator(original_func):
    def wrap_func():
        print("The wrapping starts here.")
        original_func()
        print("The wrapinf ends here.")
    return wrap_func

In [8]:
def need_decorator():
    print("I want decorator.")
need_decorator()

I want decorator.


In [9]:
decorated_func=decorator(need_decorator)

In [10]:
decorated_func()

The wrapping starts here.
I want decorator.
The wrapinf ends here.


In [13]:
@decorator
def need2_decorator():
    print("I want 2nd decorator.")
need2_decorator()

The wrapping starts here.
I want 2nd decorator.
The wrapinf ends here.


In [173]:
def add_one(func):
    def wrapper(*args):
        result=func(*args)
        return result+1
    return wrapper
        

In [174]:
@add_one
def cube(n):
    return n**3
print(cube(2))

9


In [5]:
def mult_2(func):
    def wrapper(*args,**kwargs):
        result=func(*args)
        result=result*2
        return result
    return wrapper

def add_3(func):
    def wrapper(*args,**kwargs):
        result=func(*args,**kwargs)
        result+=3
        return result
    return wrapper

@mult_2
@add_3

def same(a):
    return a
print(same(4))

14


In [67]:
def create_cubes(n):
    for i in range(n):
        print(i**3)
create_cubes(3)


0
1
8


In [63]:
for i in create_cubes(4):
    print(i)

0
1
8
27


TypeError: 'NoneType' object is not iterable

In [76]:
def fibbo(n):
    n1=0
    n2=1
    print(n1)
    print(n2)
    for i in range(2,n):
        n3=n1+n2
        n1=n2
        n2=n3
        print(n2)
        
        
fibbo(10)       

0
1
1
2
3
5
8
13
21
34


In [77]:
def fib(n):
    a=0
    b=1
    for i in range(n):
        yield a
        a,b=b,a+b
    

In [78]:
for number in fib(10):
    print(number)

0
1
1
2
3
5
8
13
21
34


In [82]:
def  simple_gen():
    for x in range(3):
        yield x

In [86]:
g=simple_gen()

In [87]:
print(next(g))

0


In [88]:
print(next(g))

1


In [90]:
str1="hello"
for letter in str1:
    print(letter)

h
e
l
l
o


In [93]:
next(str1)

TypeError: 'str' object is not an iterator

In [92]:
s_iter=iter(str1)
next(s_iter)

'h'

In [ ]:
next(s_iter)

In [94]:
def prev_1(n):
    for i in range(n):
        yield i-1

In [95]:
prev_1(4)

<generator object prev_1 at 0x000001D1F2863A70>

In [96]:
list(prev_1(5))

[-1, 0, 1, 2, 3]

In [98]:
for i in prev_1(4):
    print(i)

-1
0
1
2


In [99]:
import random
def random_integer(n,low,high):
    for i in range(n):
        yield random.randint(low,high)

for i in random_integer(5,10,100):
    print(i)
    

18
23
91
71
16


In [100]:
def square(n):
    for i in range(1,n+1):
        yield i**2
        
for i in square(4):
    print(i)
        

1
4
9
16


In [104]:
s1="Hi! I am Smarth"
s1_iter=iter(s1)



In [106]:
next(s1_iter)

'H'

In [107]:
l1=[ x**2 for x in range(5) if x%2==0]

In [109]:
l1

[0, 4, 16]

In [132]:
class Animal:
    def speak(self):
        print("I am an animal")
class dog(Animal):
    def __init__(self,breed):
        self.breed=breed
    def eat(self):
        print("I eat legs.")
d1=dog("Labrador")

class cat(dog):
    
    def __init__(self):
        pass
    def eyes(self):
        print("I have sharp eyes")

        
    

In [133]:
d1.speak()

I am an animal


In [134]:
c1=cat()
c1.eat()

I eat legs.


In [142]:
class Line:
    def __init__(self,coor1,coor2):
        self.coor1=coor1
        self.coor2=coor2
    def distance(self):
        x1,y1=self.coor1
        x2,y2=self.coor2
        dist=((x2-x1)**2 + (y2-y1)**2)**0.5
        return dist
    def slope(self):
        x1,y1=self.coor1
        x2,y2=self.coor2
        slope1=(y2-y1)/(x2-x1)
        return slope1
coor1=(3,2)
coor2=(8,10)
                        
li=Line(coor1,coor2)       
li.distance()

9.433981132056603

In [169]:
class Cylinder:
    def __init__(self,height=1,radius=1):
        self.height=height
        self.radius=radius
    def volume(self,height,radius):
        vol=3.14 * radius**2 *height
        return vol
        

In [170]:
c1=Cylinder()

In [171]:
c1.height

1

In [172]:
c1.volume(4,5)

314.0

In [164]:
def cylinder(height=1,radius=1):
    vol=3.14* radius**2 * height
    return vol
print(cylinder(2,4))

100.48


In [58]:
!pip install multipledispatch

In [59]:
from multipledispatch import dispatch

In [65]:
class Student:
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def add_age(self,add):
        self.age=self.age+add
    def get_age(self):
        return self.age
        

In [66]:
s1=Student("Smarth",21)
print(s1.get_age())
s1.add_age(2)
print(s1.get_age())


21
23


In [73]:
@dispatch(int,int)
def add(a,b):
    return a+b

@dispatch(str,str)
def add(a,b):
    return a+" "+b
@dispatch(int, str)
def add(a, b):
    return str(a) +" " + b

In [74]:
print(add(2,"Mangoes"))

2 Mangoes


In [76]:
add(110,12)

122

In [175]:
a=lambda  x,y,z: x+y+z

In [ ]:
def sum1(x,y,z):
    return x+y+z

In [3]:
# count of a specific char
s=""
count=0
for char in s:
    if char=="a":
        count+=1
print(count)
        
    

2


In [4]:
# length of string wothout using len() function

s=input("Enter tthe string: ")
count=0
for char in s:
    count+=1
print(count)

Enter tthe string: I love JIngle
13


In [8]:
#extract user name from email.(method-1)

s=input("Enter the email: ")
length=len(s)
# Length of @gmail.com=10 characters(slice last 9 characters)
username=s[:(length-10)]
print(username)

Enter the email: smarthkapil02@gmail.com
smarthkapil02


In [15]:
#extract user name from email.(method-2)
# use of .index method

s=input("Enter the mail: ")
pos=s.index("@")
username=s[:pos]
print(username)

Enter the mail: smarthkapil02@gmail.com
smarthkapil02


In [17]:
# remove particular character from string(using join and list) method-1

l1=[]
s=input("Enter the string: ")
a=input("Enter the character to be removed from the string: ")
for char in s:
    if char==a:
        pass
    else:
        l1.append(char)
s1="".join(l1)
print(s1)
    

Enter the string: Smarth Kapil
Enter the character to be removed from the string: a
Smrth Kpil


In [20]:
# remove particular character from string(methood-2)

s=input("Enter the string: ")
a=input("Enter the character to be removed from the string: ")
s1=""
for char in s:
    if char!=a:
        s1+=char
print(s1)

Enter the string: smarth
Enter the character to be removed from the string: a
smrth


In [18]:
# check for palindrome(method-1)

def check_palindrome(s):
    return s==s[::-1]
check_palindrome("ssaass")
    

True

In [25]:
# check for palindrome(method-2)

def check_palindrome1(s):
    for i in range(0,len(s)//2):
        if s[i]!= s[len(s)-i-1]:
            return "Not a palindrome"
            break
    else:
        return " A palindrome"
    
s=input("Enter the string: ")  
check_palindrome1(s)    

Enter the string: malayalam


' A palindrome'

In [28]:
# No. of words using split(method-1)

s=input("enter the string: ")
l=s.split()
print(len(l))

enter the string: Smarth KApil is a good boy
6


In [29]:
# No. of words  without using split(method-2)

s=input("Enter the string: ")
count=1
for char in s:
    if char==" ":
        count+=1
print("No. of words: ",count)

Enter the string: Smarth KApil is a good boy
No. of words:  6


In [31]:
# No. of words  without using split(method-3). 

s=input("Enter the string :")
temp=""
l1=[]
for char in s:
    if char!=" ":
        temp+=char
    else:
        l1.append(temp)
        temp=""

l1.append(temp)
print(l1) 
print(len(l1))

Enter the string :Smarth KAil
['Smarth', 'KAil']
2


In [33]:
#Convert string to title case(method-1).Using title() method

s=input("Enter the string :")
print(s.title())

Enter the string :Hi how are you
Hi How Are You


In [40]:
#Convert string to title case(method-2).Without using title() method
s=input("Enter the string: ")
temp=""
temp1=""
l1=s.split()
for word in l1:
    one=word[0].upper()
    two=word[1:]
    temp= temp+one+two
    temp1=temp1+temp+" "
    temp=""

print(temp1)


Enter the string: smarth kapi is a good boy
Smarth Kapi Is A Good Boy 


In [36]:
#convert integer to string

a=int(input("Enter the integer: "))
b=str(a)
print(type(a))
print(type(b))

Enter the integer: 5
<class 'int'>
<class 'str'>


Enter the string :s d f


NameError: name 'strip' is not defined

In [49]:
def upto_n(myfunc):
    def wrapper(*args):
        n=args[0]
        l1=[]
        for i in range(2,n):
            result=myfunc(i)
            if result:
                l1.append(i)
        return l1
    return wrapper

In [50]:
@upto_n
def pr_num(n):
    for i in range(2,(n//2)+1):
        if(n%i==0):
            return False
            break
    else:
        return True
print(pr_num(13))

[2, 3, 5, 7, 11]


In [54]:
l1=[2,3,4,5,6,7]
a=list(map(lambda x: x**2,l1))
print(a)

[4, 9, 16, 25, 36, 49]


In [57]:
def generator(n):
    for i in range(0,n):
        yield i
        
print(generator(10))

for i in generator(10):
    print(i)


<generator object generator at 0x000001D113490C10>
0
1
2
3
4
5
6
7
8
9


In [101]:
#multilevel inheritance(Animal->dog->cat)
class Animal:
    def __init__(self,specie):
        self.specie=specie
        
class dog(Animal):
    def __init__(self,specie,breed):
        super().__init__(specie)
        self.breed=breed
    
    def speak(self):
        return "I am a {}, my breed is {}".format(self.specie,self.breed)
    
class cat(dog):
    def __init__(self,specie,breed):
        super().__init__(specie,breed)
    def speak(self):
        return super().speak()
    
        

In [102]:
dog1=dog("Dog","labrador")

In [103]:
dog1.specie

'Dog'

In [104]:
dog1.breed

'labrador'

In [105]:
dog1.speak()

'I am a Dog, my breed is labrador'

In [106]:
cat1=cat("Cat","Russian Blue")

In [109]:
print(cat1.specie)
print(cat1.breed)


Cat
Russian Blue


In [110]:
print(cat1.speak())

I am a Cat, my breed is Russian Blue


In [112]:
# encapsulation in oops

class Account:
    def __init__(self,balance,name):
        self.__bal=balance
        self.name=name
    def get_balance(self):
        return self.__bal


In [114]:
a1=Account(500,"Smarth")

In [115]:
a1.get_balance()

500

In [116]:
a1.name

'Smarth'

In [120]:
a1.bal

AttributeError: 'Account' object has no attribute 'bal'

In [121]:
a1.balance

AttributeError: 'Account' object has no attribute 'balance'

In [119]:
a1._Account__bal

500

In [122]:
# two interface animal and run

from abc import ABC, abstractmethod

class Animal(ABC):
    
    @abstractmethod
    def speak(self):
        pass
    
class run:
    @abstractmethod
    def run(self):
        passs
        
class dog(Animal,run):
    def speak(self):
        return "Woof"
    def run(self):
        return "Dog is running"
    
    

In [123]:
d1=dog()

In [124]:
d1.speak()

'Woof'

In [125]:
d1.run()

'Dog is running'

In [136]:
l1=[1,2,1,4,3,2,4,6,5,5,3]

In [137]:
dic={}
for i in l1:
    if i in dic:
        dic[i]+=1
    else:
        dic[i]=1

In [138]:
print(dic)

{1: 2, 2: 2, 4: 2, 3: 2, 6: 1, 5: 2}


In [1]:
# ATM oops

# attributes :
#     1) balance
#     2) pin 
# methods:
#     2) deposit
#     3) withdrawal
#     4) check balance
#     5) create pin
    
class ATM:
    def __init__(self):
        self.__pin=0
        self.balance=0
        
        self.menu()
    
    def create_pin(self,pin):
        self.__pin=pin
        
    def withdrawal(self,withdraw):
        if self.balance>0:
            self.balance=self.balance-withdraw
            return "Balance left is {}".format(self.balance)
        else:
            return "No sufficient bank balance"
        
    def check_balance(self):
        return "Balance is {}".format(self.balance)
    
    
    def deposit(self,deposit_money):
        self.balance=self.balance+deposit_money
        return "New balance is: {}".format(self.balance)
    
    def menu(self):
        while True:
            user_input=int(input("""
            1) Enter 1 to create pin
            2) Enter 2 to deposit money
            3) Enter 3 to withdraw money
            4) Enter 4 to check balance
            5) Enter 5 to exit
            """))
            
            if user_input==1:
                self.create_pin(int(input("Enter the pin: ")))
            if user_input==2:
                print(self.deposit(int(input("Enter the amount for deposit"))))
            if user_input==3:
                print(self.withdrawal(int(input("Enter amount to be withdrawan: "))))
            if user_input==4:
                print(self.check_balance())
            if user_input==5:
                print("exit")
                break
            
            
    
    
        
        
        
       
    
        

In [2]:
a1=ATM()


            1) Enter 1 to create pin
            2) Enter 2 to deposit money
            3) Enter 3 to withdraw money
            4) Enter 4 to check balance
            5) Enter 5 to exit
            1
Enter the pin: 123

            1) Enter 1 to create pin
            2) Enter 2 to deposit money
            3) Enter 3 to withdraw money
            4) Enter 4 to check balance
            5) Enter 5 to exit
            4
Balance is 0

            1) Enter 1 to create pin
            2) Enter 2 to deposit money
            3) Enter 3 to withdraw money
            4) Enter 4 to check balance
            5) Enter 5 to exit
            2
Enter the amount for deposit220
New balance is: 220

            1) Enter 1 to create pin
            2) Enter 2 to deposit money
            3) Enter 3 to withdraw money
            4) Enter 4 to check balance
            5) Enter 5 to exit
            3
Enter amount to be withdrawan: 100
Balance left is 120

            1) Enter 1 to create pin
       

In [3]:
# Class v/s static methods
class car:
    brand="Toyota"
    
    def __init__(self):
        pass
    @staticmethod
    def sound():
        return "Sounds amazing"
    @classmethod
    def change_brand(cls,brand):
        cls.brand=brand
       

In [4]:
car.brand

'Toyota'

In [5]:
car.change_brand("Mclaren")
car.brand

'Mclaren'

In [7]:
car.sound()

'Sounds amazing'

In [6]:
l1=[1,2,3,4,5,6,7,8]
a=map(lambda x: x**2, l1)
b=list(a)
b

[1, 4, 9, 16, 25, 36, 49, 64]

In [7]:
#first filter then map

l2=[1,2,3,4,5,6,7,8,9]
result=map(lambda x: x**2,filter(lambda x: x>2,l2))
print(list(result))

[9, 16, 25, 36, 49, 64, 81]


In [11]:
# first map then filter

l1=[1,2,3,4,5,6,7,8]
a=map(lambda x: x**2, l1)
b=filter(lambda x: x>10,a)
print(list(b))

[16, 25, 36, 49, 64]


# Practice questions on oops

In [2]:
# Write a Python program to create a Vehicle class with max_speed 
# and mileage instance attributes.

class Vehicle:
    def __init__(self,max_speed,mileage):
        self.max_speed=max_speed
        self.mileage=mileage

v1=Vehicle(100,20)        
print(v1.max_speed)
print(v1.mileage)

100
20


In [5]:
# Create a Vehicle class without any variables and methods

class vehicle:
    pass # default constructor is run automatically
v2=vehicle
print(v2)

<class '__main__.vehicle'>


In [7]:
# Create a child class Bus that will inherit all of the variables and 
# methods of the Vehicle class

class Vehicle:

    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
        
class Bus(Vehicle):
    pass

        
b1=Bus("VOlvo",100,20)
print(b1.max_speed)
print(b1.mileage)
print(b1.name)

100
20
VOlvo


In [8]:
# Create a Bus class that inherits from the Vehicle class. 
# Give the capacity argument of Bus.seating_capacity() a default 
# value of 50.

class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers"
    

    
class Bus(Vehicle):
    def seating_capacity(self, capacity=50):
        self.capacity=capacity
        return f"The seating capacity of a {self.name} is {capacity} passengers"

b1=Bus("VOlvo",100,20)
print(b1.seating_capacity())
        
    

The seating capacity of a VOlvo is 50 passengers


In [11]:
# Define a class attribute”color” with a default value white. 
# I.e., Every Vehicle should be white.

class Vehicle:
    
    color="white"
    
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    pass

class Car(Vehicle):
    pass


b1=Bus("VOlvo",100,20)
print(b1.color)

c1=Car("Supra",260,3)
print(c1.color)

white
white


In [12]:
# Create a Bus child class that inherits from the Vehicle class. 
# The default fare charge of any vehicle is seating capacity * 100. 
# If Vehicle is Bus instance, we need to add an extra 10% on full fare 
# as a maintenance charge. So total fare for bus instance will become 
# the final amount = total fare + 10% of the total fare.

# Note: The bus seating capacity is 50. so the final fare amount 
# should be 5500. You need to override the fare() method of a 
# Vehicle class in Bus class.

class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

    def fare(self):
        return self.capacity * 100

class Bus(Vehicle):
    def fare(self):
        return (self.capacity * 100) + (.1 * self.capacity * 100)

School_bus = Bus("School Volvo", 12, 50)
print("Total Bus fare is:", School_bus.fare())

Total Bus fare is: 5500.0


In [13]:
# Write a program to determine which class a given Bus object 
# belongs to.

class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)
type(School_bus)


__main__.Bus

In [14]:
# Determine if School_bus is also an instance of the Vehicle class

class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

class Bus(Vehicle):
    pass

School_bus = Bus("School Volvo", 12, 50)
isinstance(School_bus,Vehicle)

True

# Exercise 1: Modeling a Bank Account

Financial applications commonly use OOP principles. This exercise models a simple bank account as a Python class.

First, identify the attributes and behaviors of a bank account:

Attributes: account number, account holder name, balance
Behaviors: depositing, withdrawing, checking balance
Next, define a BankAccount class with an initializer taking account number, name, and initial deposit as parameters. Include methods to deposit, withdraw, and check balances:

In [24]:
class BankAccount:
    def __init__(self,acc_num,name,bal):
        self.__acc_num=acc_num
        self.__name=name
        self.__bal=bal
        
        self.menu() #using method insisde class itself.
    
    def deposit(self,deposit):
        print("Amount before deposit: ", self.__bal)
        self.__bal= self.__bal+deposit
        print("Amount after deposit: ", self.__bal)
    
    def withdraw(self,amount):
        if self.__bal<amount:
            print("Low balance")
            print("Available balance is :",self.__bal)
        else:
            print("Amount before withdraw: ", self.__bal)
            self.__bal= self.__bal-amount
            print("Amount after withdraw: ", self.__bal)
            
    def check_balance(self):
        print("The current amount in your account is: ",self.__bal)
    
    def menu(self):
        while True:
            user_input=int(input("""
            1) Enter 1 to deposit money
            2) Enter 2 to withdraw money
            3) Enter 3 to check balance
            4) Enter 4 to exit
            """))
            
            if user_input==1:
                self.deposit(int(input("Enter the amount for deposit")))
            if user_input==2:
                self.withdraw(int(input("Enter amount to be withdrawan: ")))
            if user_input==3:
                self.check_balance()
            if user_input==4:
                print("exit")
                break

a1=BankAccount(123,"Smarth",600)


            1) Enter 1 to deposit money
            2) Enter 2 to withdraw money
            3) Enter 3 to check balance
            4) Enter 4 to exit
            3
The current amount in your account is:  600

            1) Enter 1 to deposit money
            2) Enter 2 to withdraw money
            3) Enter 3 to check balance
            4) Enter 4 to exit
            3
The current amount in your account is:  600

            1) Enter 1 to deposit money
            2) Enter 2 to withdraw money
            3) Enter 3 to check balance
            4) Enter 4 to exit
            2
Enter amount to be withdrawan: 200
Amount before withdraw:  600
Amount after withdraw:  400

            1) Enter 1 to deposit money
            2) Enter 2 to withdraw money
            3) Enter 3 to check balance
            4) Enter 4 to exit
            1
Enter the amount for deposit500
Amount before deposit:  400
Amount after deposit:  900

            1) Enter 1 to deposit money
            2) Enter 2 t

In [34]:
class Student:
    def __init__(self, name, iden):
        self.name = name
        self.iden = iden
        self.courses = []
        
    def enrolling(self, course):
        self.courses.append(course)  
        print(f"List of courses student {self.name} is enrolled in: ", [course.title for course in self.courses])
        
    def dropping(self, course):
        for c in self.courses:
            if c.title == course.title:
                print(f"List of courses before withdrawal for {self.name}: ", [course.title for course in self.courses])
                self.courses.remove(c)  

                print(f"List of courses after withdrawal for {self.name}: ", [course.title for course in self.courses])
                course.drop_student(self)
    def view(self):
        print(f"List of courses {self.name} is enrolled in: ", [course.title for course in self.courses])


class Course:
    def __init__(self, title, instructor, max_students):
        self.title = title
        self.instructor = instructor
        self.max_students = max_students
        self.student_list = []
        
    def add_student(self, student):
        if len(self.student_list) < self.max_students:
            print(f"List of students enrolled in {self.title} before adding: ", [s.name for s in self.student_list])
            self.student_list.append(student) 
            student.enrolling(self)  
            print(f"List of students enrolled in {self.title} after adding: ", [s.name for s in self.student_list])
        else:
            print(f"Course {self.title} is already full")

    def drop_student(self, student):
        print(f"List of students enrolled in {self.title} before removing: ", [s.name for s in self.student_list])
        self.student_list.remove(student)  
        print(f"List of students enrolled in {self.title} after removing: ", [s.name for s in self.student_list])
            
    def view_students(self):
        print(f"List of students enrolled in {self.title}: ", [s.name for s in self.student_list])



math101 = Course("Calculus", "Dr. Smith", 3)
john = Student("John Doe", "12345")
jane = Student("Jane Doe", "67890")
mark = Student("Mark Lee", "11111")

math101.add_student(john)
math101.add_student(jane)
math101.add_student(mark)


math101.view_students()

john.dropping(math101)  


math101.view_students()

john.view()


List of students enrolled in Calculus before adding:  []
List of courses student John Doe is enrolled in:  ['Calculus']
List of students enrolled in Calculus after adding:  ['John Doe']
List of students enrolled in Calculus before adding:  ['John Doe']
List of courses student Jane Doe is enrolled in:  ['Calculus']
List of students enrolled in Calculus after adding:  ['John Doe', 'Jane Doe']
List of students enrolled in Calculus before adding:  ['John Doe', 'Jane Doe']
List of courses student Mark Lee is enrolled in:  ['Calculus']
List of students enrolled in Calculus after adding:  ['John Doe', 'Jane Doe', 'Mark Lee']
List of students enrolled in Calculus:  ['John Doe', 'Jane Doe', 'Mark Lee']
List of courses before withdrawal for John Doe:  ['Calculus']
List of courses after withdrawal for John Doe:  []
List of students enrolled in Calculus before removing:  ['John Doe', 'Jane Doe', 'Mark Lee']
List of students enrolled in Calculus after removing:  ['Jane Doe', 'Mark Lee']
List of stu

In [35]:
jane.dropping(math101)

List of courses before withdrawal for Jane Doe:  ['Calculus']
List of courses after withdrawal for Jane Doe:  []
List of students enrolled in Calculus before removing:  ['Jane Doe', 'Mark Lee']
List of students enrolled in Calculus after removing:  ['Mark Lee']


In [36]:
math101.view_students()

List of students enrolled in Calculus:  ['Mark Lee']


# Basic python coding

In [45]:
# Print the Sum of a Current Number and a Previous number
#rolling sum

low=int(input("Enter the lower range value: "))
high=int(input("Enter the higher range value: "))
sum1=0
for num in range(low,high):
    if i==low:
        print(low)
        sum1=low
    else:
        sum1=sum1+num
        print(sum1)
        
        
    
    
    
        
        
    

10
21
33
46
60


In [40]:
# characters at even index numbers

s="Python"
for index,char in enumerate(s):
    if index%2==0:
        print(index,char)

0 P
2 t
4 o


In [46]:
# Remove first n characters from a string

s=input("Enter the string: ")
a=int(input("Enter the no. of characters to be removed: "))
s=s[a::]
print(s)

Enter the string: Smarth
Enter the no. of characters to be removed: 2
arth


In [49]:
# Find the number of occurrences of a substring in a string

count=0
s=input("Enter the string: ")
l1=s.split()
for word in l1:
    if word=="Emma":
        count+=1
    else:
        pass
print("The count is: ",count)

Enter the string: Emma stone is great but Emma watson is best
The count is:  2


In [56]:
for i in range(1,6):
    for j in range(0,i):
        print(i,end=" ")
    print("\n")

1 

2 2 

3 3 3 

4 4 4 4 

5 5 5 5 5 



In [59]:
a=int(input("Enter the number: "))
b=str(a)
b=b[::-1]
l1=[]
for char in b:
    l1.append(char)
c=" ".join(l1)   
print(c)

Enter the number: 123
3 2 1


In [60]:
# tble from 1 to 10
for i in range(1,11):
    for j in range(1,11):
        print(i,"*",j,"=",i*j )
    

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90
10 * 1 = 10
10 * 2 = 20


In [54]:
## sequence matters as : if  i%3==0 and i%5==0: comes in last then 
# fizz will be printed for n=15 because first it will be checked 
# if it is divisile by 3 and if not then for divisible by 
# 5 and at last for divisibility both 3 and 5

for i in range(1,20):
    if i%3==0 and i%5==0:
        print("FIzzBuzz")
    elif i%3==0:
        print("Fizz")
    elif(i%5==0):
        print("Buzz")
    else:
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FIzzBuzz
16
17
Fizz
19


In [63]:
# downward half-pyramid pattern of stars

for i in range(5,0,-1):
    for j in range(0,i):
        print("*", end=" ")
    print("\n")
        
    

* * * * * 

* * * * 

* * * 

* * 

* 



# File Handling

In [110]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt")

In [111]:
data=f.read() 

In [112]:
data

'Hi. My name is Smarth KApil.\nI am an AI ML intern at netsmartz. creating this file for I/O operation'

In [113]:
f.close()

In [114]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt")

In [115]:
data1=f.read(100)

In [116]:
data1

'Hi. My name is Smarth KApil.\nI am an AI ML intern at netsmartz. creating this file for I/O operation'

In [117]:
f.close()
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt")

In [118]:
line1=f.readline()

In [119]:
line1

'Hi. My name is Smarth KApil.\n'

In [120]:
f.close()
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt")

In [121]:
line1=f.readline()
line2=f.readline()
print(line1)
print(line2)

Hi. My name is Smarth KApil.

I am an AI ML intern at netsmartz. creating this file for I/O operations learning.


In [125]:
f.close()


# Writing a file

In [128]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt") as f:
    content=f.read()
print(content)
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","a") as f:
    f.write("I am working at netsmartz.\nI wan to excel in ml")


1,2,3,4,5,6,7


In [129]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt") as f:
    content=f.read()
print(content)


1,2,3,4,5,6,7I am working at netsmartz.
I wan to excel in ml


In [131]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r+") as f:
    f.write("Hello")



In [132]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt") as f:
    content=f.read()
print(content)

Hello,3,4,5,6,7I am working at netsmartz.
I wan to excel in ml


In [4]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","w+") as f:
    f.write("Hello I am Smarth")
    f.seek(0)
    content=f.read()
print(content)

Hello I am Smarth


In [ ]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt","w")

In [127]:
f.write("I want to learn python basics.123")

33

In [128]:
f.close()

In [129]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt","r")

In [130]:
data=f.read()

In [131]:
data

'I want to learn python basicsI want to learn python basics.123'

In [132]:
f.close()

In [133]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt","a")
f.write("\n I also want to become proficient in AI-ML")
f.close()

In [137]:
f=open(r"C:\Users\smart\Downloads\IO TESTING.txt","r")
data=f.read()
print(data)
f.close()

I want to learn python basicsI want to learn python basics.123
 I also want to become proficient in AI-ML


In [138]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
print(data)

I want to learn python basicsI want to learn python basics.123
 I also want to become proficient in AI-ML


In [139]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
new_data=data.replace("I","Smarth")
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","w") as f:
    f.write(new_data)

In [140]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
print(data)

Smarth want to learn python basicsSmarth want to learn python basics.123
 Smarth also want to become proficient in ASmarth-ML


In [144]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","a") as f:
    f.write("\n1,2,3,4,5,6,7")
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
print(data)

Smarth want to learn python basicsSmarth want to learn python basics.123
 Smarth also want to become proficient in ASmarth-ML1,2,3,4,5,6,7
1,2,3,4,5,6,7


In [145]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","w") as f:
    f.write("\n1,2,3,4,5,6,7")
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
print(data)


1,2,3,4,5,6,7


In [148]:
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
    print(data)
    num=""
    for i in range(len(data)):
        if data[i]==",":
            print(num)
            num=""
        else:
            num+=data[i]
    print(num)


1,2,3,4,5,6,7

1
2
3
4
5
6
7


In [151]:
count=0
with open(r"C:\Users\smart\Downloads\IO TESTING.txt","r") as f:
    data=f.read()
    nums=data.split(",")
    print(nums)
    
    for val in nums:
        if int(val)%2==0:
            count+=1
print(count)

['\n1', '2', '3', '4', '5', '6', '7']
3


In [4]:
def square(n):
    for i in range(0,n):
        return i
square(3)

0

In [6]:
def func():
    global x
    x = 45
    print(x)

func()
print(x)

45
45


In [8]:
from abc import ABC,abstractmethod

In [ ]:
def animal(ABC):
    @abstractmethod
    def speak(self):
        return "Meow"
    @staticmethod
    def run():
        return "I am running"
a1=animal()
    

In [24]:
class animal(ABC):
    @abstractmethod
    def speak(self):
        pass

class cat(animal):
    def speak(self):
        return "meow"
    

In [25]:
c1=cat()

In [26]:
print(c1)
print(c1.speak())

meow


In [ ]:
#Duck typing

class Cat:
    def speak(self):
        return "Meow"

class Dog:
    def speak(self):
        return "Bark"

def animal_sound(animal):
    return animal.speak()

cat = Cat()
dog = Dog()
print(animal_sound(cat))  # Output: Meow
print(animal_sound(dog)) 


# Exception handling

In [27]:
a=b

NameError: name 'b' is not defined

In [28]:
try:
    a=b
except NameError:
    print("Name error occured")
    

Name error occured


In [1]:
# Exception  is the baseclass for built-in exceptions

try:
    a=b
except Exception as e:
    print(e)
    

name 'b' is not defined


In [2]:
# write child classes first. before base class Exception.BAse class 
# exception will handle all kinds of exception except 
# system level exceptions like SystemExit, KeyboardInterrupt

try:
    a=b
except NameError:
    print("Does not define variable b")
except Exception as e:
    print(e)

Does not define variable b


In [3]:
try:
    a=1
    b="s"
    c=b+a
except NameError:
    print("Does not define variable b")
except Exception as e:
    print(e)

can only concatenate str (not "int") to str


In [5]:
# type error can be defined in seperate except block
a=1
b="s"
c=b+a

TypeError: can only concatenate str (not "int") to str

In [3]:
try:
    a=1
    b="s"
    c=b+a
except NameError:
    print("Does not define variable b")
except TypeError:
    print("There is a type error. chack data tyoes")
except Exception as e:
    print(e)

There is a type error. chack data tyoes


In [10]:
# use else block to execute the block of code if no error occured

try:
    a=10
    b=20
    c=a+b
except Exceptions as e:
    print(e)

else:
    print(c)
    
    

30


In [2]:
# us of finally to execute the block certainly. Error occured or not 
# does not matter.

try:
    a=10
    b="s"
    c=a+b
except Exception as e:
    print(e)

finally:
    print("Code executed")

unsupported operand type(s) for +: 'int' and 'str'
Code executed


In [10]:
# use of try finally except

try:
    a=int(input("Enter the code: "))
    b=int(input("Enter the code: "))
    c= a==b
except Exception as e:
    print(e)
    
else:
    print(c)

finally:
    print("Cod executed")

Enter the code: 123
Enter the code: sa
invalid literal for int() with base 10: 'sa'
Cod executed


In [33]:
#raise custom exceptions

class Error(Exception):
    pass

class dobException(Error):
    pass


In [36]:
year=int(input("Enter the year of birth: "))
age=2025-year
try:
    if age>20 and age <=30:
        print("The age is correct")
    else:
        raise dobException

except dobException:
    print("The year is not valid.")
    


Enter the year of birth: 2002
The age is correct


In [41]:
# use of assert statement
num=10
assert num>10,"Value is not greater than 20"

AssertionError: Value is not greater than 20

In [40]:
try:
    num=int(input("Enter the number greater than 10: "))
    assert num>10
except AssertionError:
    print("Enter number greater than 10")
else:
    print("Number is greater than 10")
    

Enter the number greater than 10: 4
Enter number greater than 10


In [9]:
def count(n):
    for i in range(n):
        yield i
a=count(3)
print(a)
print(type(a))
print(next(a))
print(next(a))
print(next(a))

<generator object count at 0x000001DACEE8C190>
<class 'generator'>
0
1
2


In [22]:
def inc_20(func):
    def wrapper(*args,**kwargs):
        l1=[]
        for i in range(0,*args):
            result= func(i)
            l1.append(result+20)
        return l1
    return wrapper
            
        

@inc_20
def square(num):
    return num**2
square(3)

[20, 21, 24]

In [1]:
def inc_20(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)  # Call the original function with passed arguments
        return result + 20  # Add 20 to the result
    return wrapper

@inc_20
def multiply(a, b):
    return a * b

print(multiply(2, 3))  # Output should be (2 * 3) + 20 = 26

26


In [4]:
def welcome():
    print('hii')
w=welcome()

hii


# Closures in python

In [14]:
def outer(msg):
    count=1
    def inner():
        print(msg)
        print(count)
    return inner()
outer("Smarth")

Smarth
1


In [19]:
def outer(msg):
    count=1
    def inner():
        print(msg)
        print(count)
    return inner
outer("Smarth")

<function __main__.outer.<locals>.inner()>

In [17]:
def outer(msg):
    count=1
    def inner():
        print(msg)
        print(count)
    return inner
a=outer("Smarth")

In [18]:
a()

Smarth
1


In [26]:
def dec_20(func):
    def wrapper(*args,**kwargs):
        print("Wrapper Started")
        result=func(*args)
        return result-20
    return wrapper

@dec_20
def square(n):
    return n*n
result=square(5)
print(square(20))
type(result)

Wrapper Started
Wrapper Started
380


int

In [27]:
l1=[x**2 for x in range(1,3)]
l1

[1, 4]

In [28]:
dict={x:x+1 for x in range(5)}
print(dict)

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5}


In [29]:
def generator(n):
    for i in range(0,n):
        yield i
generator(5)

<generator object generator at 0x00000203EE3F8C80>

In [31]:
class Animal:
    def __init__(self,name):
        self.__name=name       
    def get_name(self):
        return self.__name

a1=Animal("Smarth")
        
        

In [32]:
a1.get_name()

'Smarth'

In [33]:
a1.name

AttributeError: 'Animal' object has no attribute 'name'

In [35]:
a1._Animal__name

'Smarth'

In [36]:
s=(1,2,3,4)
s[:3]

(1, 2, 3)

In [37]:
s[1]

2

In [39]:
s1={1,2,3,4}
s1[2]

TypeError: 'set' object is not subscriptable

In [44]:
class Error(Exception):
    pass
class Jingle(Error):
    pass

In [49]:
try:
    a=2
    b=2
    if a==b:
        print("Correct value")
    else:
        raise Jingle
except Jingle:
    print("JIngle super intelligent. Can't compete")
else:
    print("jingleji intelligent than deepseek")
finally:
    print("jingle is the most intelligent")

class Error(Exception):
    pass
class Jingle(Error):
    pass


Correct value
jingleji intelligent than deepseek
jingle is the most intelligent


In [55]:
a=lambda x:x**2

In [57]:
for i in range(5):
    print(a(i))

0
1
4
9
16


In [14]:
a=map(lambda x:x*4,range(5))
print(a)

In [89]:
from functools import reduce
a=lambda x: x*3
b=lambda x: x%2==0
c=lambda x,y: x+y

d=map(a,range(5))
print(d)

e=filter(b,d)
print(list(e))

# f=reduce(c,e,0)
# print(f)


[0, 6, 12]


In [95]:
def generator(n):
    for i in range(n):
        yield i
a=generator(5)

    

In [97]:
for i in a:
    print(i)
    


In [98]:
# error is generated after
# all the element are iterated but for loop handles that. If want 
# to traverse again firt re-reun the generator and ten execute for loop

In [103]:
t1=(1,2,2,3,4)
t1.count(3)

1

In [110]:
t1=(t1)+(4)

TypeError: can only concatenate tuple (not "int") to tuple

In [109]:
t1

(1, 2, 2, 3, 4, 4, 5)

In [111]:
t1=(t1)+(4,)
t2=t1[0:6]
t2

(1, 2, 2, 3, 4, 4)

In [112]:
for i,n in enumerate(t1):
    print(i,n)


0 1
1 2
2 2
3 3
4 4
5 4
6 5
7 4


In [113]:
type(enumerate(t1))

enumerate

In [116]:
l1=[1,1,2,3,4,5,3,2,6,5,7,8,9]
dict={}
for i in l1:
    if i in dict:
        dict[i]+=1
    else:
        dict[i]=1
print(dict)

{1: 2, 2: 2, 3: 2, 4: 1, 5: 2, 6: 1, 7: 1, 8: 1, 9: 1}


In [125]:
# merge two ditinaries

d1={"name": "Smarth","age":21}
d2={"roll no.":114}
d3={**d1,**d2}
print("Dictionary 1",d1)
print("Dictionary 2",d2)
print("Dictionary 3",d3)
d1.update(d2)
print(d1)

Dictionary 1 {'name': 'Smarth', 'age': 21}
Dictionary 2 {'roll no.': 114}
Dictionary 3 {'name': 'Smarth', 'age': 21, 'roll no.': 114}
{'name': 'Smarth', 'age': 21, 'roll no.': 114}


# Numpy module

In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr=np.array(range(1,6))
arr

array([1, 2, 3, 4, 5])

In [9]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [12]:
arr=np.array([1,2,3,4,5], ndmin=3)
arr

array([[[1, 2, 3, 4, 5]]])

In [17]:
arr.shape

(1, 1, 5)

In [18]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [19]:
arr.shape

(1, 1, 5)

In [20]:
arr.ndim

3

In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
arr.shape

(2, 4)

In [24]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [28]:
arr[:,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
b=arr.reshape(4,2)

In [32]:
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [34]:
print(b[2:,1])
print(type(b[2:,1]))

[6 8]
<class 'numpy.ndarray'>


In [37]:
arr[:,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [38]:
arr=np.array([1,2,3,4,5], ndmin=3)
arr

array([[[1, 2, 3, 4, 5]]])

In [39]:
arr.ndim

3

In [40]:
arr.size

5

In [42]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])

In [43]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [48]:
# get 4,5,6,8
arr[1:3,2:4]


array([[4, 5],
       [6, 8]])

In [50]:
# get 3,4,5

arr[0,2:]

array([3, 4, 5])

In [51]:
arr[1,1:4]

array([3, 4, 5])

In [54]:
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [53]:
arr=np.array(range(1,10,2))
arr

array([1, 3, 5, 7, 9])

In [55]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [56]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[3:]=100

In [58]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [59]:
arr1=arr
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [61]:
arr1[3:]=500
print(arr1)
print(arr)

[  1   2   3 500 500 500 500 500 500]
[  1   2   3 500 500 500 500 500 500]


In [62]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr1=arr.copy()
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr1[3:]=100
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [64]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr=np.array([1,2,3],ndmin=3)
arr

array([[[1, 2, 3]]])

In [73]:
arr[0][0][1]

2

In [78]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [77]:
l1=[1,2,3]
l1=l1
l1

[1, 2, 3, 2]

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr[arr<6]

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)
arr[arr%3==0]

[1 2 3 4 5 6 7 8 9]


array([3, 6, 9])

In [88]:
3%3

0

In [7]:
a=np.ones(4)

print(type(a[0]))
print(a)

<class 'numpy.float64'>
[1. 1. 1. 1.]


In [10]:
b=np.ones((2,5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
b=np.ones((2,5),dtype=int)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
x=20
def func(y):
    global x
    return x
print(func(10))

20


In [21]:
x=20
def func(y):
    global x
    x=x+30
    return x
print(func(10))
print(x)

50
50


In [24]:
def func(**kwargs):
    return kwargs["name"]
func(name="Smarth")

'Smarth'

In [27]:
def func(**kwargs):
    return kwargs.get("name")# " " are important
func(name="Smarth")

'Smarth'

In [ ]:
from multipledispatch import dispatch


@dispatch(int, int)
def add(a: int, b: int):
    print(f"Sum of integers: {a + b}")

@dispatch(str, str)
def add(a: str, b: str):
    print(f"Concatenation of strings: {a + b}")

In [32]:
arr_3d=np.array([[[1,2,3],
         [4,5,6],
         [ 7,8,9]],
        
        [[10,11,12],
         [13,14,15],
         [16,17,18]]])

In [38]:
sum_axis_0_3d = arr_3d.sum(axis=0)
sum_axis_0_3d 

array([[11, 13, 15],
       [17, 19, 21],
       [23, 25, 27]])

In [33]:
sum_axis_1_3d = arr_3d.sum(axis=1)
sum_axis_1_3d 

array([[12, 15, 18],
       [39, 42, 45]])

In [37]:
sum_axis_2_3d = arr_3d.sum(axis=2)
sum_axis_2_3d 

array([[ 6, 15, 24],
       [33, 42, 51]])

In [36]:
arr_2d=np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [40]:
sum_axis_0=arr_2d.sum(axis=0)
sum_axis_0

array([ 6,  8, 10, 12])

In [41]:
sum_axis_1=arr_2d.sum(axis=1)
sum_axis_1

array([10, 26])